name: Docker Push kaspool-app image

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}:v2408.1b

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Docker Login
        run: echo "${{ secrets.GB_KASPOOL_TOKEN }}" | docker login ${{ env.REGISTRY }} --username coinchimp --password-stdin
     
      - name: Docker Build
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .
        
      - name: Docker Push
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


